intel/auto-round

docs/acc.md

add hqq acc data.md

---

auto_round/autoround.py
auto_round/export/export_to_itrex/export.py
auto_round/utils.py

revert convert_dtype, baichuan_support and hpu autocast

---

docs/acc.md

update omniquant accuracy

---

auto_round/export/export_to_itrex/export.py
examples/language-modeling/main.py
examples/language-modeling/run_xpu.sh

Support XPU export

---

examples/language-modeling/eval/evaluation.py
examples/language-modeling/eval/utils.py
examples/language-modeling/eval_legacy/evaluation.py

Adjust the default eval dtype by selecting from the model config

Adjust the default eval dtype by selecting from the model_dir config

---

auto_round/autoround.py
auto_round/export/export_to_itrex/export.py

Add `transformers.Conv1D`  check

support `transformers.Conv1D` packing

---

auto_round/autoround.py
auto_round/utils.py

fix falcon no attention_mask issue with disable_trust_remote_code

fix falcon quant issue with disable_trust_remote_code

---

auto_round/auto_quantizer.py
auto_round_extension/qbits/qlinear_qbits.py

as title, for better user experience.

Qbits related log

---

auto_round/calib_dataset.py
examples/language-modeling/README.md

dataset = datasetname1:split=train+val:num=256,datasetname2:concat=True:num=128,datasetname3:concat
We use ',' to split datasets and ':' to split parameters of a dataset.

support calibration dataset concat

---

auto_round/export/export_to_autogptq.py
auto_round/export/export_to_autoround/export.py

The GPTQ API parses the quantize_config.json while Transformers parses the config.json

revert the gptq format code to fix the regression

---

auto_round/data_type/__init__.py
auto_round/data_type/int.py
auto_round/data_type/mxfp.py
auto_round/data_type/register.py
auto_round/data_type/utils.py
auto_round/quantizer.py
auto_round/utils.py
auto_round/version.py
examples/language-modeling/main.py
test/test_autoround.py

add initial support of mxfp4

---

auto_round/autoround.py
auto_round/export/export_to_autogptq/export.py
auto_round/export/export_to_autoround/export.py
auto_round/export/export_to_itrex/export.py
auto_round/special_model_handler.py
auto_round/utils.py
examples/language-modeling/README.md
examples/language-modeling/main.py
examples/multimodal-modeling/Llava/main.py
examples/multimodal-modeling/Llava/run_autoround.sh
examples/multimodal-modeling/Qwen-VL/main.py
examples/multimodal-modeling/Qwen-VL/run_autoround.sh
test/test_block_names.py

fix mixtral-8x7b model quantization issue

Fix multimodal and moe issue

---

auto_round/quantizer.py

bugfix of groupsize dismatch with weight shape

---

auto_round/autoround.py
examples/language-modeling/main.py
test/test_autoround_acc.py

move set_seed func from example to autoround source code, Add UT to test the reproducibility of accuracy

Add setseed in autoround

---

auto_round/data_type/int.py

Limit the scale minimum value not to 0
tested on common models(>=10)
currently, only effects Qwen2-57B-A14B-Instruct model

Limit the scale minimum value not to 0

---

auto_round/export/export_to_itrex/export.py
examples/language-modeling/main.py
test/test_autoround_export_to_itrex.py

The XPU backend has aligned its convert format with Hugging Face. auto-round should follow up on this change.
Testing on XPU is done

update xpu format exporting

---

examples/language-modeling/eval_042/evaluation.py

refine eval_042 to enable parallelize evaluation

---

auto_round/data_type/int.py
auto_round/quantizer.py

on 125m, 30% speedup
7B models, 15%-20% speedup

refine the code and the speedup is notable

---

README.md

update readme for cpu inference

---

.azure-pipelines/scripts/ut/run_ut.sh
auto_round/export/export_to_itrex/bit_packer.py
auto_round/export/export_to_itrex/model_wrapper.py
requirements.txt
test/test_woq_linear.py

Porting the Numba-based packing for `export.itrex.WoQLinear`.
cc @Kaihui-intel 
cc@Xuehao, Please be aware that I added `numba` and `tbb` to `requirements.txt`.

Port Numba-based packing from INC

---

setup.py

Background: for `auto-round-hpu`, it can be installed from the source before Torch is installed.

[HPU]Enhance installation check

---

README.md
auto_round/script/llm.py
auto_round/script/mllm.py
auto_round/utils.py
test/test_cuda_before_release.py

fixed https://github.com/intel/auto-round/issues/359

add gpu test

---

README.md
auto_round/autoround.py
auto_round/backend.py
auto_round/calib_dataset.py
auto_round/script/llm.py
auto_round/script/mllm.py
auto_round/utils.py
docs/step_by_step.md
test/test_calib_dataset.py

fixed https://github.com/intel/auto-round/issues/366
workaround for https://github.com/intel/auto-round/issues/388

enhance calibration dataset and add awq pre quantization warning

---

auto_round/auto_quantizer.py
auto_round/data_type/mxfp.py
auto_round/export/export_to_awq/export.py
auto_round_extension/ipex/qlinear_ipex_awq.py
test/test_export.py
test/test_generation.py

add use_auto_round_format arg, force load other quant format to autoround

Support force loading into autoround Format

---

auto_round/export/export_to_autogptq/export.py
auto_round/export/export_to_autogptq/qlinear_triton.py
auto_round/export/export_to_awq/utils.py

20x for awq and 4x for gptq packing speedup

---

auto_round/auto_quantizer.py
auto_round/backend.py
auto_round/utils.py
auto_round_extension/ipex/qlinear_ipex_awq.py
auto_round_extension/ipex/qlinear_ipex_gptq.py
test/test_export.py
test_xpu/test_autoround.py

TODO:  issue=xpu could not be automatically used when not using auto backend

support xpu in tuning and inference

---

README.md
auto_round/__init__.py
auto_round/autoround.py
auto_round/export/export_to_autoround/export.py
auto_round/inference/__init__.py
auto_round/inference/auto_quantizer.py
auto_round/inference/backend.py
auto_round/inference/convert_model.py
auto_round_extension/cuda/qlinear_tritonv2.py
auto_round_extension/cuda/qlinear_tritonv2_zp.py
test/test_generation.py
test/test_load_awq_gptq.py
test_cuda/test_auto_round_format.py

Done:  remind better backend,3bits support, test auto backend, gptq_awq format support
TODO:refine config.json/divide_group_size_checker/

refine inference step 2

---

README.md
auto_round/autoround.py
auto_round/calib_dataset.py
auto_round/script/llm.py

no ---tasks no eval
--tasks use default tasks
--tasks xxx use customized tasks

use --tasks to control evaluation enabling

---

README.md
auto_round/autoround.py
auto_round/data_type/nvfp.py
auto_round/export/export_to_autogptq/export.py
auto_round/export/export_to_autoround/export.py
auto_round/export/export_to_awq/export.py
auto_round/inference/auto_quantizer.py
auto_round/inference/backend.py
auto_round/inference/convert_model.py
auto_round/utils.py
auto_round/wrapper.py
docs/step_by_step.md
test/test_act_quantization.py
test/test_block_names.py

1 add nvfp4
2 refine xpu requirements info
3 refine config.json exporting
4 fix not trigger rtn immediately packing issue
5 fix act_bits and act_dtype setting issue
6 add readme of multiple gpu tuning

refine xpu requirement/config json and fix several issues

---

auto_round/autoround.py
auto_round/data_type/fp8.py
auto_round/data_type/register.py
auto_round/data_type/utils.py
auto_round/export/export_to_autogptq/export.py
auto_round/export/export_to_autoround/export.py
auto_round/export/export_to_autoround/export_to_fp8_woq.py
auto_round/export/export_to_autoround/qlinear_triton_act.py
auto_round/export/export_to_awq/export.py
auto_round/inference/auto_quantizer.py
auto_round/utils.py
auto_round/wrapper.py

python3 -m auto_round
--model "/models/DeepSeek-R1-Distill-Llama-8B"
--group_size 0
--output_dir
"/data5/wenhuach"
--iters 0
--data_type "fp8"
data_type could be changed to fp8_e5m2, fp8_unit_scale, fp8_e5m2_unit_scale
group_size 0 per-tensor,
-1 per-channel,
positive group_wise,

FP8 WOQ export

---

README.md
auto_round/data_type/gguf.py
auto_round/export/export_to_gguf/packing.py

basically no impact on q2ks, maybe we could remove the searching part

fix critic bug of gguf tuning

---

auto_round/__main__.py
auto_round/autoround.py
auto_round/export/export_to_autogptq/export.py
auto_round/export/export_to_autoround/export.py
auto_round/export/export_to_awq/export.py
auto_round/export/export_to_gguf/export.py
auto_round/export/export_to_itrex/export.py
auto_round/export/export_to_llmcompressor/export.py
auto_round/mllm/autoround_mllm.py
auto_round/mllm/processor.py
auto_round/mllm/template.py
auto_round/mllm/utils.py
auto_round/script/llm.py
auto_round/special_model_handler.py
auto_round/utils.py

* merge mllm and llm script
* support for Mistral 3.2 series

update autoround mllm and support Mistral 3.2 series

---

auto_round/autoround.py
auto_round/export/export_to_autogptq/export.py
auto_round/export/export_to_autoround/export.py
auto_round/inference/convert_model.py
auto_round/script/llm.py
auto_round/script/mllm.py
auto_round/utils.py
auto_round_extension/torch/qlinear_torch.py
docs/mxnv_acc.md
test/test_cpu/test_autoround.py
test/test_cpu/test_autoround_acc.py
test/test_cpu/test_cli_usage.py
test/test_cpu/test_export.py

fix several regressions including lm-head quantization, 3bit asym torch backend,etc
